# Generated by Django 4.1.7 on 2024-03-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
